# Intitial EDA

In [59]:
import pandas as pd 
import pandas as pd
import duckdb

df = pd.read_csv("data_files/alvsjo_data.csv")
df

,Namn,Typ,Kategori,Gata,Nr,Lat,Lon
0,Konstfack,university,Skola,LM Ericssons Väg,14,59.299773,17.994210
1,Marino,restaurant,Restaurang,Klubbacken,51,59.305325,17.963290
2,Hemköp Stockholm Älvsjö,supermarket,Matbutik,Sjättenovembervägen,208,59.278752,18.002280
3,NaN,parking,Parkering,NaN,NaN,59.292349,17.985708
4,McDonald's,fast_food,Snabbmat,NaN,NaN,59.293074,18.001211
...,...,...,...,...,...,...,...
819,NaN,parking,Parkering,NaN,NaN,59.301074,18.011193
820,NaN,parking,Parkering,NaN,NaN,59.304636,18.029399
821,Aspuddens skola,school,Skola,Blommensbergsvägen,166,59.309309,17.997874
822,NaN,parking,Parkering,NaN,NaN,59.309750,18.029463
823,NaN,parking,Parkering,NaN,NaN,59.309716,18.023791

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 824 entries, 0 to 823
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Namn      449 non-null    str
 1   Typ       824 non-null    str
 2   Kategori  824 non-null    str
 3   Gata      135 non-null    str
 4   Nr        131 non-null    str
 5   Lat       824 non-null    float64
 6   Lon       824 non-null    float64
dtypes: float64(2), str(5)
memory usage: 45.2 KB

In [61]:
df.dtypes 

# This gives the insight on the data types - and also makes me question why  nr  is str?

Namn            str
Typ             str
Kategori        str
Gata            str
Nr              str
Lat         float64
Lon         float64
dtype: object

In [62]:
df.describe()

              Lat         Lon
count  824.000000  824.000000
mean    59.294608   17.994744
std      0.011369    0.023342
min     59.264904   17.942848
25%     59.285467   17.974851
50%     59.294143   17.999034
75%     59.304444   18.012304
max     59.317949   18.036724

In [48]:
# T stands for transpose: rows  <-> cols (switch places)
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Lat,824.0,59.294608,0.011369,59.264904,59.285467,59.294143,59.304444,59.317949
Lon,824.0,17.994744,0.023342,17.942848,17.974851,17.999034,18.012304,18.036724

### Rows & Columns

In [49]:
df.columns

Index(['Namn', 'Typ', 'Kategori', 'Gata', 'Nr', 'Lat', 'Lon'], dtype='str')

In [50]:
len(df.columns)

7

In [51]:
df.index

RangeIndex(start=0, stop=824, step=1)

In [52]:
#Adding 1 because it doesnt count row 0 
len(df.index) + 1

825

### Check for missing or Null values

In [53]:
duckdb.sql("""--sql 
    select *
    from df 
    where 
        namn IS NULL OR 
        typ IS NULL OR
        kategori IS NULL OR
        gata IS NULL OR
        nr IS NULL OR 
        lat IS NULL OR
        lon IS NULL
           
""").df()

           Namn         Typ    Kategori Gata   Nr        Lat        Lon
0           NaN     parking   Parkering  NaN  NaN  59.292349  17.985708
1    McDonald's   fast_food    Snabbmat  NaN  NaN  59.293074  18.001211
2     Sushi Bar  restaurant  Restaurang  NaN  NaN  59.292424  17.967934
3           NaN     parking   Parkering  NaN  NaN  59.264904  17.983771
4           NaN     parking   Parkering  NaN  NaN  59.271886  17.999430
..          ...         ...         ...  ...  ...        ...        ...
691         NaN     parking   Parkering  NaN  NaN  59.289355  17.997289
692         NaN     parking   Parkering  NaN  NaN  59.301074  18.011193
693         NaN     parking   Parkering  NaN  NaN  59.304636  18.029399
694         NaN     parking   Parkering  NaN  NaN  59.309750  18.029463
695         NaN     parking   Parkering  NaN  NaN  59.309716  18.023791

[696 rows x 7 columns]

In [54]:


duckdb.sql("""--sql 
    SELECT
        COUNT(*) - COUNT(namn)     AS namn_nulls,
        COUNT(*) - COUNT(typ)      AS typ_nulls,
        COUNT(*) - COUNT(kategori) AS kategori_nulls,
        COUNT(*) - COUNT(gata)     AS gata_nulls,
        COUNT(*) - COUNT(nr)       AS nr_nulls,
        COUNT(*) - COUNT(lat)      AS lat_nulls,
        COUNT(*) - COUNT(lon)      AS lon_nulls
    FROM df
""").df()

,namn_nulls,typ_nulls,kategori_nulls,gata_nulls,nr_nulls,lat_nulls,lon_nulls
0,375,0,0,689,693,0,0

### Unique values in typ & kategori

In [55]:
len(df.Kategori.unique())

11

In [56]:
len(df.Typ.unique())

14

In [57]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
819    False
820    False
821    False
822    False
823    False
Length: 824, dtype: bool

In [58]:
df.drop_duplicates()

,Namn,Typ,Kategori,Gata,Nr,Lat,Lon
0,Konstfack,university,Skola,LM Ericssons Väg,14,59.299773,17.994210
1,Marino,restaurant,Restaurang,Klubbacken,51,59.305325,17.963290
2,Hemköp Stockholm Älvsjö,supermarket,Matbutik,Sjättenovembervägen,208,59.278752,18.002280
3,NaN,parking,Parkering,NaN,NaN,59.292349,17.985708
4,McDonald's,fast_food,Snabbmat,NaN,NaN,59.293074,18.001211
...,...,...,...,...,...,...,...
819,NaN,parking,Parkering,NaN,NaN,59.301074,18.011193
820,NaN,parking,Parkering,NaN,NaN,59.304636,18.029399
821,Aspuddens skola,school,Skola,Blommensbergsvägen,166,59.309309,17.997874
822,NaN,parking,Parkering,NaN,NaN,59.309750,18.029463
823,NaN,parking,Parkering,NaN,NaN,59.309716,18.023791

### Check categories

In [63]:
df['Kategori'].value_counts()

Kategori
Parkering        380
Skola            144
Restaurang       138
Snabbmat          54
Kafé              40
Matbutik          26
Tandläkare        15
Apotek            11
Trafikskola        8
Vårdcentral        7
Fysioterapeut      1
Name: count, dtype: int64