In [1]:
import pandas as pd

population_df = pd.read_excel(r'data_files\1.2-folkmangd-den-31-dec-2010-2034.xlsx')
population_df = population_df.dropna(how='all')
population_df = population_df.dropna(axis=1, how='all')
population_df = population_df.iloc[3:17]
population_df = population_df.iloc[:, [0, 4]]
population_df.columns = ['area', 'population']
population_df['population'] = population_df['population'].round(0).astype(int)
population_df.head()

                 area  population
3           Västerort      254678
4               Järva       95220
5  Hässelby-Vällingby       76340
6              Bromma       83118
8         Inre staden      356620

In [2]:
import pandas as pd

crime_df = pd.read_excel(r'data_files\1.63-anmalda-brott-2024.xlsx')
crime_df = crime_df.dropna(how='all')
crime_df = crime_df.dropna(axis=1, how='all')
crime_df = crime_df.iloc[5:19]
crime_df = crime_df.iloc[:, [0, 1]]
crime_df.columns = ['area', 'reported_crime']
crime_df['reported_crime'] = pd.to_numeric(crime_df['reported_crime'])
crime_df['reported_crime'] = crime_df['reported_crime'].round(0).astype(int)
crime_df.head()

                  area  reported_crime
5            Västerort           45769
6                Järva           15950
7   Hässelby-Vällingby           15944
8               Bromma           13875
10         Inre staden           85022

In [3]:
import pandas

migration_df = pd.read_excel(r'data_files\1.20-in--och-utflyttade-samt-inomflyttningar-2024.xlsx')
migration_df = migration_df.dropna(how='all')
migration_df = migration_df.dropna(axis=1, how='all')
migration_df = migration_df.iloc[6:20]
migration_df = migration_df.iloc[:, [0, 4, 8, 9]]
migration_df.columns = ['area', 'in_migration', 'out_migration', 'net_migration']
migration_df.head()

                  area in_migration out_migration net_migration
6            Västerort        27481         25710          1771
7                Järva        14136         11904          2232
8   Hässelby-Vällingby         8110          8437          -327
9               Bromma         9140          9274          -134
11         Inre staden        34254         36181         -1927

In [4]:
merged_table = population_df.merge(crime_df, on='area').merge(migration_df, on='area')

merged_table.to_csv('data_stockholm_2024.csv', index=False)

In [9]:
import pandas as pd

crime_2024_2026_df = pd.read_excel(r'data_files\brottsstatistik_hägersten-älvsjö.xlsx')

crime_2024_2026_df

,Anmälda brott,Unnamed: 1,Brottsförebyggande rådet
0,NaN,NaN,NaN
1,NaN,2024,2025
2,NaN,Helår,Helår
3,NaN,/100 000 inv,/100 000 inv
4,Stadsdelsområde Bromma (Sthlm),NaN,NaN
5,3-7 kap. Brott mot person,NaN,NaN
6,3 kap. Brott mot liv och hälsa,658,667
7,3-7 kap. Brott mot person,NaN,NaN
8,4 kap. Brott mot frihet och frid,1396,1372
9,3-7 kap. Brott mot person,NaN,NaN
10,5 kap. Ärekränkningsbrott,76,78
11,3-7 kap. Brott mot person,NaN,NaN
12,6 kap. Sexualbrott,244,253
13,3-7 kap. Brott mot person,NaN,NaN
14,7 kap. Brott mot familj,5,8
15,8-12 kap. Brott mot förmögenhet,NaN,NaN
16,"8 kap. Stöld, rån m.m.",3507,3072
17,8-12 kap. Brott mot förmögenhet,NaN,NaN
18,9 kap. Bedrägeri och annan oredlighet,1622,1647
19,8-12 kap. Brott mot förmögenhet,NaN,NaN
20,10 kap. Förskingring och annan trolöshet,93,125
21,8-12 kap. Brott mot förmögenhet,NaN,NaN
22,11 kap. Brott mot borgenärer m.m.,0,0
23,8-12 kap. Brott mot förmögenhet,NaN,NaN
24,12 kap. Skadegörelsebrott,6878,3957
25,NaN,NaN,NaN
26,NaN,NaN,NaN
27,Stadsdelsområde Bromma (Sthlm),NaN,NaN
28,I juni 2016 har redovisningen av folkmängd änd...,NaN,NaN

In [36]:
import pandas as pd

crime_hägersten_älvsjö = pd.read_excel(r'data_files\brottsstatistik_hägersten-älvsjö.xlsx')
crime_hägersten_älvsjö = crime_hägersten_älvsjö.iloc[[6, 8, 10, 12, 14, 16, 18, 20, 22, 24]]
crime_hägersten_älvsjö.columns = ['lagrum', '2024', '2025']
crime_hägersten_älvsjö['område'] = 'Hägersten-Älvsjö'
crime_hägersten_älvsjö['lagrum'] = crime_hägersten_älvsjö['lagrum'].str.rstrip('.')

crime_hägersten_älvsjö

                                      lagrum  2024  2025            område
6             3 kap. Brott mot liv och hälsa   810   825  Hägersten-Älvsjö
8           4 kap. Brott mot frihet och frid  1482  1507  Hägersten-Älvsjö
10                 5 kap. Ärekränkningsbrott    77    79  Hägersten-Älvsjö
12                        6 kap. Sexualbrott   262   279  Hägersten-Älvsjö
14                   7 kap. Brott mot familj    14     9  Hägersten-Älvsjö
16                     8 kap. Stöld, rån m.m  3297  2981  Hägersten-Älvsjö
18     9 kap. Bedrägeri och annan oredlighet  1441  1899  Hägersten-Älvsjö
20  10 kap. Förskingring och annan trolöshet    92    92  Hägersten-Älvsjö
22          11 kap. Brott mot borgenärer m.m     2     1  Hägersten-Älvsjö
24                 12 kap. Skadegörelsebrott  5843  5593  Hägersten-Älvsjö

In [ ]:
import pandas as pd

crime_bromma_df = pd.read_excel(r'data_files\brottsstatistik_bromma.xlsx')
crime_bromma_df = crime_bromma_df.iloc[[6, 8, 10, 12, 14, 16, 18, 20, 22, 24]]
crime_bromma_df.columns = ['lagrum', '2024', '2025']
crime_bromma_df['område'] = 'Bromma'
crime_bromma_df['lagrum'] = crime_bromma_df['lagrum'].str.rstrip('.')

crime_bromma_df

                                      lagrum  2024  2025  område
6             3 kap. Brott mot liv och hälsa   658   667  Bromma
8           4 kap. Brott mot frihet och frid  1396  1372  Bromma
10                 5 kap. Ärekränkningsbrott    76    78  Bromma
12                        6 kap. Sexualbrott   244   253  Bromma
14                   7 kap. Brott mot familj     5     8  Bromma
16                     8 kap. Stöld, rån m.m  3507  3072  Bromma
18     9 kap. Bedrägeri och annan oredlighet  1622  1647  Bromma
20  10 kap. Förskingring och annan trolöshet    93   125  Bromma
22          11 kap. Brott mot borgenärer m.m     0     0  Bromma
24                 12 kap. Skadegörelsebrott  6878  3957  Bromma

In [41]:
import csv

merge_crime_df = pd.concat([crime_hägersten_älvsjö, crime_bromma_df], ignore_index=True)

merge_crime_df.to_csv('brottsstatistik_bromma_hägersten-älvsjö.csv', index=None, sep=';')

In [35]:
import pandas as pd

population_df = pd.read_csv(r'data_files\stockholm_folkm_regso_2024.csv')

filtered_population = population_df[population_df['stadsdelsomrade'] == 'Bromma']

filtered_population_agg = filtered_population.groupby('Statistikområde').sum()

filtered_population

FileNotFoundError: [Errno 2] No such file or directory: 'data_files\\stockholm_folkm_regso_2024.csv'

In [48]:
import pandas as pd

df = pd.read_csv(r'data_files\stockholm_folkm_regso_2021_2024.csv')

df['Statistikområde'] = df['Statistikområde'].str.split(' ', n=1).str[1]

df['Statistikområde'].str.strip()

df.to_csv(r'data_files\folkmangd_clean.csv', index=False)

In [51]:
import pandas as pd

df = pd.read_csv(r'data_files\folkmangd_clean.csv')

df.groupby('Statistikområde')['value'].sum()

Statistikområde
Bromma    79315
Name: value, dtype: int64