In [1]:
import pandas as pd

population_df = pd.read_excel(r'data_files\1.2-folkmangd-den-31-dec-2010-2034.xlsx')
population_df = population_df.dropna(how='all')
population_df = population_df.dropna(axis=1, how='all')
population_df = population_df.iloc[3:17]
population_df = population_df.iloc[:, [0, 4]]
population_df.columns = ['area', 'population']
population_df['population'] = population_df['population'].round(0).astype(int)
population_df.head()

                 area  population
3           Västerort      254678
4               Järva       95220
5  Hässelby-Vällingby       76340
6              Bromma       83118
8         Inre staden      356620

In [2]:
import pandas as pd

crime_df = pd.read_excel(r'data_files\1.63-anmalda-brott-2024.xlsx')
crime_df = crime_df.dropna(how='all')
crime_df = crime_df.dropna(axis=1, how='all')
crime_df = crime_df.iloc[5:19]
crime_df = crime_df.iloc[:, [0, 1]]
crime_df.columns = ['area', 'reported_crime']
crime_df['reported_crime'] = pd.to_numeric(crime_df['reported_crime'])
crime_df['reported_crime'] = crime_df['reported_crime'].round(0).astype(int)
crime_df.head()

                  area  reported_crime
5            Västerort           45769
6                Järva           15950
7   Hässelby-Vällingby           15944
8               Bromma           13875
10         Inre staden           85022

In [3]:
import pandas

migration_df = pd.read_excel(r'data_files\1.20-in--och-utflyttade-samt-inomflyttningar-2024.xlsx')
migration_df = migration_df.dropna(how='all')
migration_df = migration_df.dropna(axis=1, how='all')
migration_df = migration_df.iloc[6:20]
migration_df = migration_df.iloc[:, [0, 4, 8, 9]]
migration_df.columns = ['area', 'in_migration', 'out_migration', 'net_migration']
migration_df.head()

                  area in_migration out_migration net_migration
6            Västerort        27481         25710          1771
7                Järva        14136         11904          2232
8   Hässelby-Vällingby         8110          8437          -327
9               Bromma         9140          9274          -134
11         Inre staden        34254         36181         -1927

In [4]:
merged_table = population_df.merge(crime_df, on='area').merge(migration_df, on='area')

merged_table.to_csv('data_stockholm_2024.csv', index=False)