In [3]:
import pandas as pd 

import pandas as pd

df = pd.read_csv("alvsjo_data.csv")

df

,Namn,Typ,Kategori,Gata,Nr,Lat,Lon
0,Konstfack,university,Skola,LM Ericssons Väg,14,59.299773,17.994210
1,Marino,restaurant,Restaurang,Klubbacken,51,59.305325,17.963290
2,Hemköp Stockholm Älvsjö,supermarket,Matbutik,Sjättenovembervägen,208,59.278752,18.002280
3,NaN,parking,Parkering,NaN,NaN,59.292349,17.985708
4,McDonald's,fast_food,Snabbmat,NaN,NaN,59.293074,18.001211
...,...,...,...,...,...,...,...
820,NaN,parking,Parkering,NaN,NaN,59.301074,18.011193
821,NaN,parking,Parkering,NaN,NaN,59.304636,18.029399
822,Aspuddens skola,school,Skola,Blommensbergsvägen,166,59.309309,17.997874
823,NaN,parking,Parkering,NaN,NaN,59.309750,18.029463
824,NaN,parking,Parkering,NaN,NaN,59.309716,18.023791

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Namn      450 non-null    str
 1   Typ       825 non-null    str
 2   Kategori  825 non-null    str
 3   Gata      135 non-null    str
 4   Nr        131 non-null    str
 5   Lat       825 non-null    float64
 6   Lon       825 non-null    float64
dtypes: float64(2), str(5)
memory usage: 45.2 KB

In [5]:
df.columns

Index(['Namn', 'Typ', 'Kategori', 'Gata', 'Nr', 'Lat', 'Lon'], dtype='str')

In [6]:
df.describe()

              Lat         Lon
count  825.000000  825.000000
mean    59.294621   17.994793
std      0.011368    0.023371
min     59.264904   17.942848
25%     59.285472   17.974856
50%     59.294183   17.999042
75%     59.304445   18.012308
max     59.317949   18.036724

In [7]:
# T stands for transpose: rows  <-> cols (switch places)
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Lat,825.0,59.294621,0.011368,59.264904,59.285472,59.294183,59.304445,59.317949
Lon,825.0,17.994793,0.023371,17.942848,17.974856,17.999042,18.012308,18.036724