# EDA - Brottsstatistik

## Initial EDA

In [11]:
import pandas as pd
import duckdb
import matplotlib

df = pd.read_excel('../data_files/brottsstatistik_2024_2026.xls', header=None)

df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,Anmälda brott,NaN,Brottsförebyggande rådet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2023,2023,2023,2023,2023,2023,2023,2023,2024,...,2024,2024,2025,2025,2025,2025,2025,2025,2025,2025
3,NaN,Kvartal 1,Kvartal 1,Kvartal 2,Kvartal 2,Kvartal 3,Kvartal 3,Kvartal 4,Kvartal 4,Kvartal 1,...,Kvartal 4,Kvartal 4,Kvartal 1,Kvartal 1,Kvartal 2,Kvartal 2,Kvartal 3,Kvartal 3,Kvartal 4,Kvartal 4
4,NaN,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,...,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv
5,Stadsdelsområde Bromma (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3 kap. Brott mot liv och hälsa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,därav misshandel inkl. grov,121,147,154,187,134,163,97,118,120,...,126,152,107,129,141,170,118,142,135,162
9,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.shape

(139, 25)

In [15]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24],
      dtype='int64')

In [14]:
df.iloc[2:5, :10]

,0,1,2,3,4,5,6,7,8,9
2,NaN,2023,2023,2023,2023,2023,2023,2023,2023,2024
3,NaN,Kvartal 1,Kvartal 1,Kvartal 2,Kvartal 2,Kvartal 3,Kvartal 3,Kvartal 4,Kvartal 4,Kvartal 1
4,NaN,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal

### Kommentar:
* Rad 0-4: Headers/metadata
* Totalt antal brott: kolumn 1, 3, 5..
* Brott per capita: kolumn 2, 4, 6..

- remove first row
- change headers